name: street_vendors
description: "Flutter mobile app for street ambulant vendors."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

## DEPENDENCIES | PACKAGES
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  # State management
  get: ^4.6.5
  get_storage: ^2.1.1
  connectivity_plus: ^2.2.2
  # UI packages
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8
  # Firebase packages
  firebase_core: ^2.26.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/onboarding_images/
    - assets/images/placeholder_images/
    - assets/icons/
    - assets/fonts/
    - assets/videos/

  ##fonts:



