// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHsxE7IHil2k0JeN7jy4dQRW6Jy_vkGs',
    appId: '1:673337612791:android:cb84affc2d4518ab2bb6f2',
    messagingSenderId: '673337612791',
    projectId: 'streeter-727f1',
    storageBucket: 'streeter-727f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKm8SZea9oZNK2IiCHD8cFlC2MSLQhK8',
    appId: '1:673337612791:ios:eb2543460742e60e2bb6f2',
    messagingSenderId: '673337612791',
    projectId: 'streeter-727f1',
    storageBucket: 'streeter-727f1.appspot.com',
    androidClientId: '673337612791-5njhbfvm4l24v6tbhibng9nb6gqfaupt.apps.googleusercontent.com',
    iosClientId: '673337612791-q70dp4ah9tfulf0h0kj8j2j93r5rpks2.apps.googleusercontent.com',
    iosBundleId: 'mx.com.wolvensoft.streetvendors.streetVendors',
  );
}
